# Generated by Django 6.0.3 on 2026-03-22 16:58

from django.conf import settings
from django.db import migrations
from django.db.models import Count, Min


def remove_duplicate_project_freelancer_pairs(apps, schema_editor):
    Proposal = apps.get_model('proposals', 'Proposal')
    duplicate_groups = (
        Proposal.objects.values('project_id', 'freelancer_id')
        .annotate(first_id=Min('id'), pair_count=Count('id'))
        .filter(pair_count__gt=1)
    )

    for group in duplicate_groups:
        (
            Proposal.objects.filter(
                project_id=group['project_id'],
                freelancer_id=group['freelancer_id'],
            )
            .exclude(id=group['first_id'])
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('proposals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_project_freelancer_pairs,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('project', 'freelancer')},
        ),
    ]
